name: Debug CI
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential cmake pkg-config libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-tools gstreamer1.0-plugins-base gstreamer1.0-plugins-good cppcheck
          version: 1.0
      - run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DGST_METADATA_BUILD_EXAMPLES=ON -DGST_METADATA_BUILD_TESTS=ON
      - run: |
          set +e
          cppcheck --project=build/compile_commands.json --enable=warning,style,performance --suppressions-list=.cppcheck-suppressions --error-exitcode=1 --inline-suppr 2>&1 > /tmp/out.txt
          echo "EXIT: $?" >> /tmp/out.txt
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -B debug-output
          cp /tmp/out.txt debug-cppcheck-output.txt
          git add debug-cppcheck-output.txt
          git commit -m "cppcheck output"
          git push origin debug-output --force
